//GREETING

//dialogue1
import greeting_dialogue1_01_l from "../../languages/yakut/greeting/audio/dialogue1/здравствуйте.mp3"
import greeting_dialogue1_01_r from "../../languages/yakut/greeting/audio/dialogue1/добрый день.mp3"
import greeting_dialogue1_02_l from "../../languages/yakut/greeting/audio/dialogue1/извините можно войти_.mp3"
import greeting_dialogue1_02_r from "../../languages/yakut/greeting/audio/dialogue1/вы на экз пришли_.mp3"
import greeting_dialogue1_03_l from "../../languages/yakut/greeting/audio/dialogue1/да на экз.mp3"
import greeting_dialogue1_03_r from "../../languages/yakut/greeting/audio/dialogue1/да пожалуйста проходите.mp3"
import greeting_dialogue1_04_l from "../../languages/yakut/greeting/audio/dialogue1/спасибо.mp3"
import greeting_dialogue1_04_r from "../../languages/yakut/greeting/audio/dialogue1/ой прошу прощения подождите немного.mp3"
import greeting_dialogue1_05_l from "../../languages/yakut/greeting/audio/dialogue1/хорошо.mp3"

//dialogue2
import greeting_dialogue2_01_l from "../../languages/yakut/greeting/audio/dialogue2/давайте познакомимся как вас зовут.mp3"
import greeting_dialogue2_01_r from "../../languages/yakut/greeting/audio/dialogue2/меня зовут айаал.mp3"
import greeting_dialogue2_02_l from "../../languages/yakut/greeting/audio/dialogue2/вы откуда сами.mp3"
import greeting_dialogue2_02_r from "../../languages/yakut/greeting/audio/dialogue2/я приехал из якутии.mp3"
import greeting_dialogue2_03_l from "../../languages/yakut/greeting/audio/dialogue2/сколько вам лет.mp3"
import greeting_dialogue2_03_r from "../../languages/yakut/greeting/audio/dialogue2/мне уже 40.mp3"
import greeting_dialogue2_04_l from "../../languages/yakut/greeting/audio/dialogue2/вы женаты_.mp3"
import greeting_dialogue2_04_r from "../../languages/yakut/greeting/audio/dialogue2/я женат.mp3"
import greeting_dialogue2_05_l from "../../languages/yakut/greeting/audio/dialogue2/есть ли у вас дети.mp3"
import greeting_dialogue2_05_r from "../../languages/yakut/greeting/audio/dialogue2/у меня 1 ребенок.mp3"
import greeting_dialogue2_06_l from "../../languages/yakut/greeting/audio/dialogue2/где вы работаете.mp3"
import greeting_dialogue2_06_r from "../../languages/yakut/greeting/audio/dialogue2/работаю в школе учителем.mp3"
import greeting_dialogue2_07_l from "../../languages/yakut/greeting/audio/dialogue2/я рад знакомству с вами.mp3"
import greeting_dialogue2_07_r from "../../languages/yakut/greeting/audio/dialogue2/приятно познакомиться.mp3"

//dialogue 3
import greeting_dialogue3_01_l from "../../languages/yakut/greeting/audio/dialogue3/добрый день.mp3"
import greeting_dialogue3_01_r from "../../languages/yakut/greeting/audio/dialogue3/здравстввуйте.mp3"
import greeting_dialogue3_02_l from "../../languages/yakut/greeting/audio/dialogue3/я айталина дьулустановна.mp3"
import greeting_dialogue3_02_r from "../../languages/yakut/greeting/audio/dialogue3/меня зовут ньургун.mp3"
import greeting_dialogue3_03_l from "../../languages/yakut/greeting/audio/dialogue3/как пишется ваше имя.mp3"
import greeting_dialogue3_03_r from "../../languages/yakut/greeting/audio/dialogue3/ньургун.mp3"
import greeting_dialogue3_04_l from "../../languages/yakut/greeting/audio/dialogue3/вы казах_.mp3"
import greeting_dialogue3_04_r from "../../languages/yakut/greeting/audio/dialogue3/нет я саха.mp3"
import greeting_dialogue3_05_l from "../../languages/yakut/greeting/audio/dialogue3/откуда вы.mp3"
import greeting_dialogue3_05_r from "../../languages/yakut/greeting/audio/dialogue3/я из якутии.mp3"
import greeting_dialogue3_06_l from "../../languages/yakut/greeting/audio/dialogue3/из какого вы города.mp3"
import greeting_dialogue3_06_r from "../../languages/yakut/greeting/audio/dialogue3/якутск.mp3"
import greeting_dialogue3_07_l from "../../languages/yakut/greeting/audio/dialogue3/назовите свой адрес.mp3"
import greeting_dialogue3_07_r from "../../languages/yakut/greeting/audio/dialogue3/березовая улица 20 кв 145.mp3"
import greeting_dialogue3_08_l from "../../languages/yakut/greeting/audio/dialogue3/большое спасибо вы работаете в производственном.mp3"
import greeting_dialogue3_08_r from "../../languages/yakut/greeting/audio/dialogue3/нет я работаю сахатранснефтегаз.mp3"
import greeting_dialogue3_09_l from "../../languages/yakut/greeting/audio/dialogue3/кто вы по профессии.mp3"
import greeting_dialogue3_09_r from "../../languages/yakut/greeting/audio/dialogue3/инженер.mp3"
import greeting_dialogue3_10_l from "../../languages/yakut/greeting/audio/dialogue3/вы женаты_.mp3"
import greeting_dialogue3_10_r from "../../languages/yakut/greeting/audio/dialogue3/да.mp3"
import greeting_dialogue3_11_l from "../../languages/yakut/greeting/audio/dialogue3/у вас есть дети.mp3"
import greeting_dialogue3_11_r from "../../languages/yakut/greeting/audio/dialogue3/да у меня две дочери.mp3"
import greeting_dialogue3_12_l from "../../languages/yakut/greeting/audio/dialogue3/сколько вам лет.mp3"
import greeting_dialogue3_12_r from "../../languages/yakut/greeting/audio/dialogue3/мне 34.mp3"
import greeting_dialogue3_13_l from "../../languages/yakut/greeting/audio/dialogue3/в каком месяце у вас день рождения.mp3"
import greeting_dialogue3_13_r from "../../languages/yakut/greeting/audio/dialogue3/ноябрь.mp3"
import greeting_dialogue3_14_l from "../../languages/yakut/greeting/audio/dialogue3/чем занимаетесь.mp3"
import greeting_dialogue3_14_r from "../../languages/yakut/greeting/audio/dialogue3/кроссворды люблю решать.mp3"
import greeting_dialogue3_15_l from "../../languages/yakut/greeting/audio/dialogue3/отлтчно ты занимаешься спортом_.mp3"
import greeting_dialogue3_15_r from "../../languages/yakut/greeting/audio/dialogue3/да я катаюсь на велосипеде.mp3"
import greeting_dialogue3_16_l from "../../languages/yakut/greeting/audio/dialogue3/обычно до скольких вы работаете.mp3"
import greeting_dialogue3_16_r from "../../languages/yakut/greeting/audio/dialogue3/до 6 часов вечера.mp3"
import greeting_dialogue3_17_l from "../../languages/yakut/greeting/audio/dialogue3/в какие дни вы можете посещать уроки англ.mp3"
import greeting_dialogue3_17_r from "../../languages/yakut/greeting/audio/dialogue3/в пн и чт сколько стоит один урок_.mp3"
import greeting_dialogue3_18_l from "../../languages/yakut/greeting/audio/dialogue3/400 рублей два раза в неделю.mp3"
import greeting_dialogue3_18_r from "../../languages/yakut/greeting/audio/dialogue3/хорошо.mp3"
import greeting_dialogue3_19_l from "../../languages/yakut/greeting/audio/dialogue3/не могли бы вы дать мне свой номер тлф пожалуйста.mp3"
import greeting_dialogue3_19_r from "../../languages/yakut/greeting/audio/dialogue3/конечно 1234567.mp3"
import greeting_dialogue3_20_l from "../../languages/yakut/greeting/audio/dialogue3/адрес ваше электронной почты.mp3"
import greeting_dialogue3_20_r from "../../languages/yakut/greeting/audio/dialogue3/1234567@email.com.mp3"
import greeting_dialogue3_21_l from "../../languages/yakut/greeting/audio/dialogue3/спасибо теперь давайте познакомимся с другими студентами.mp3"
import greeting_dialogue3_21_r from "../../languages/yakut/greeting/audio/dialogue3/с удовольствием.mp3"

//dictionary
import greeting_dictionary001 from "../../languages/yakut/greeting/audio/dictionary/доброе утро.mp3"
import greeting_dictionary002 from "../../languages/yakut/greeting/audio/dictionary/добрый день.mp3"
import greeting_dictionary003 from "../../languages/yakut/greeting/audio/dictionary/добрый вечер.mp3"
import greeting_dictionary004 from "../../languages/yakut/greeting/audio/dictionary/здравствуйте.mp3"
import greeting_dictionary005 from "../../languages/yakut/greeting/audio/dictionary/до свидания.mp3"
import greeting_dictionary006 from "../../languages/yakut/greeting/audio/dictionary/до скорой встречи.mp3"
import greeting_dictionary007 from "../../languages/yakut/greeting/audio/dictionary/удачи.mp3"
import greeting_dictionary008 from "../../languages/yakut/greeting/audio/dictionary/пожалуйста.mp3"
import greeting_dictionary009 from "../../languages/yakut/greeting/audio/dictionary/спасибо.mp3"
import greeting_dictionary010 from "../../languages/yakut/greeting/audio/dictionary/большое спасибо.mp3"
import greeting_dictionary011 from "../../languages/yakut/greeting/audio/dictionary/спокойной ночи.mp3"
import greeting_dictionary012 from "../../languages/yakut/greeting/audio/dictionary/благодарю вас.mp3"
import greeting_dictionary013 from "../../languages/yakut/greeting/audio/dictionary/благодарю вас за помощь.mp3"
import greeting_dictionary014 from "../../languages/yakut/greeting/audio/dictionary/заранее благодарен вам.mp3"
import greeting_dictionary015 from "../../languages/yakut/greeting/audio/dictionary/за это вам спасибо.mp3"
import greeting_dictionary016 from "../../languages/yakut/greeting/audio/dictionary/спасибо за совет (помощь).mp3"
import greeting_dictionary017 from "../../languages/yakut/greeting/audio/dictionary/как я рад.mp3"
import greeting_dictionary018 from "../../languages/yakut/greeting/audio/dictionary/как приятно!.mp3"
import greeting_dictionary019 from "../../languages/yakut/greeting/audio/dictionary/извините.mp3"
import greeting_dictionary020 from "../../languages/yakut/greeting/audio/dictionary/всего наилучшего.mp3"
import greeting_dictionary021 from "../../languages/yakut/greeting/audio/dictionary/все хорошо.mp3"
import greeting_dictionary022 from "../../languages/yakut/greeting/audio/dictionary/приятно познакомиться.mp3"
import greeting_dictionary023 from "../../languages/yakut/greeting/audio/dictionary/счастливо.mp3"
import greeting_dictionary024 from "../../languages/yakut/greeting/audio/dictionary/можно спросить.mp3"
import greeting_dictionary025 from "../../languages/yakut/greeting/audio/dictionary/давайте встретимся.mp3"
import greeting_dictionary026 from "../../languages/yakut/greeting/audio/dictionary/рад вас видеть.mp3"
import greeting_dictionary027 from "../../languages/yakut/greeting/audio/dictionary/рад вас снова видеть.mp3"
import greeting_dictionary028 from "../../languages/yakut/greeting/audio/dictionary/я думаб.mp3"
import greeting_dictionary029 from "../../languages/yakut/greeting/audio/dictionary/по моему мнению.mp3"
import greeting_dictionary030 from "../../languages/yakut/greeting/audio/dictionary/как у вас дела.mp3"
import greeting_dictionary031 from "../../languages/yakut/greeting/audio/dictionary/вы завтра свободны.mp3"
import greeting_dictionary032 from "../../languages/yakut/greeting/audio/dictionary/я не забуду вашей доброты.mp3"
import greeting_dictionary033 from "../../languages/yakut/greeting/audio/dictionary/у меня плохое настроение.mp3"
import greeting_dictionary034 from "../../languages/yakut/greeting/audio/dictionary/я вас прошу.mp3"
import greeting_dictionary035 from "../../languages/yakut/greeting/audio/dictionary/можно вас побеспокоить на секунду.mp3"
import greeting_dictionary036 from "../../languages/yakut/greeting/audio/dictionary/добро пожаловать.mp3"
import greeting_dictionary037 from "../../languages/yakut/greeting/audio/dictionary/к нам пожаловали гости.mp3"
import greeting_dictionary038 from "../../languages/yakut/greeting/audio/dictionary/рад вашему приезду.mp3"
import greeting_dictionary039 from "../../languages/yakut/greeting/audio/dictionary/пожалуйста войдите.mp3"
import greeting_dictionary040 from "../../languages/yakut/greeting/audio/dictionary/пожалуйста садитесь.mp3"
import greeting_dictionary041 from "../../languages/yakut/greeting/audio/dictionary/разденьтесь снимите пальто.mp3"
import greeting_dictionary042 from "../../languages/yakut/greeting/audio/dictionary/как поживаете.mp3"
import greeting_dictionary043 from "../../languages/yakut/greeting/audio/dictionary/хорошо.mp3"
import greeting_dictionary044 from "../../languages/yakut/greeting/audio/dictionary/как ваше здоровье.mp3"
import greeting_dictionary045 from "../../languages/yakut/greeting/audio/dictionary/спасибо хорошо.mp3"
import greeting_dictionary046 from "../../languages/yakut/greeting/audio/dictionary/что нового.mp3"
import greeting_dictionary047 from "../../languages/yakut/greeting/audio/dictionary/ничего особенного.mp3"
import greeting_dictionary048 from "../../languages/yakut/greeting/audio/dictionary/как успехи.mp3"
import greeting_dictionary049 from "../../languages/yakut/greeting/audio/dictionary/спасибо с удовольствием.mp3"
import greeting_dictionary050 from "../../languages/yakut/greeting/audio/dictionary/где находится.mp3"
import greeting_dictionary051 from "../../languages/yakut/greeting/audio/dictionary/извините за опоздание.mp3"
import greeting_dictionary052 from "../../languages/yakut/greeting/audio/dictionary/извините я на секунду.mp3"
import greeting_dictionary053 from "../../languages/yakut/greeting/audio/dictionary/подождите минуту пожалуйста.mp3"
import greeting_dictionary054 from "../../languages/yakut/greeting/audio/dictionary/извините что заставил вас ждать.mp3"
import greeting_dictionary055 from "../../languages/yakut/greeting/audio/dictionary/вы говорите по якутски_1.mp3"
import greeting_dictionary056 from "../../languages/yakut/greeting/audio/dictionary/вы говорите по якутски.mp3"
import greeting_dictionary057 from "../../languages/yakut/greeting/audio/dictionary/к сожалению я не говорю по якутски.mp3"
import greeting_dictionary058 from "../../languages/yakut/greeting/audio/dictionary/я не понимаю.mp3"
import greeting_dictionary059 from "../../languages/yakut/greeting/audio/dictionary/простите пожвлуйста.mp3"
import greeting_dictionary060 from "../../languages/yakut/greeting/audio/dictionary/прошу прощения.mp3"
import greeting_dictionary061 from "../../languages/yakut/greeting/audio/dictionary/извините я сделал нечаянно.mp3"
import greeting_dictionary062 from "../../languages/yakut/greeting/audio/dictionary/да.mp3"
import greeting_dictionary063 from "../../languages/yakut/greeting/audio/dictionary/нет.mp3"
import greeting_dictionary064 from "../../languages/yakut/greeting/audio/dictionary/разрешите познакомиться.mp3"
import greeting_dictionary065 from "../../languages/yakut/greeting/audio/dictionary/как вас зовут.mp3"
import greeting_dictionary066 from "../../languages/yakut/greeting/audio/dictionary/меня зовут.mp3"
import greeting_dictionary067 from "../../languages/yakut/greeting/audio/dictionary/я васильев иван инженер по должности.mp3"
import greeting_dictionary068 from "../../languages/yakut/greeting/audio/dictionary/вы откуда сами.mp3"
import greeting_dictionary069 from "../../languages/yakut/greeting/audio/dictionary/я приехала из россии.mp3"
import greeting_dictionary070 from "../../languages/yakut/greeting/audio/dictionary/познакомьтесь это моя семья.mp3"
import greeting_dictionary071 from "../../languages/yakut/greeting/audio/dictionary/сколько вам лет.mp3"
import greeting_dictionary072 from "../../languages/yakut/greeting/audio/dictionary/мне уже 30.mp3"
import greeting_dictionary073 from "../../languages/yakut/greeting/audio/dictionary/большая ли у вас семья.mp3"
import greeting_dictionary074 from "../../languages/yakut/greeting/audio/dictionary/сколько человек.mp3"
import greeting_dictionary075 from "../../languages/yakut/greeting/audio/dictionary/вы женаты.mp3"
import greeting_dictionary076 from "../../languages/yakut/greeting/audio/dictionary/я женат.mp3"
import greeting_dictionary077 from "../../languages/yakut/greeting/audio/dictionary/я холост.mp3"
import greeting_dictionary078 from "../../languages/yakut/greeting/audio/dictionary/есть ли у вас дети.mp3"
import greeting_dictionary079 from "../../languages/yakut/greeting/audio/dictionary/у меня один ребенок.mp3"
import greeting_dictionary080 from "../../languages/yakut/greeting/audio/dictionary/у меня нет детей.mp3"
import greeting_dictionary081 from "../../languages/yakut/greeting/audio/dictionary/сколько лет сыну.mp3"
import greeting_dictionary082 from "../../languages/yakut/greeting/audio/dictionary/дети большие.mp3"
import greeting_dictionary083 from "../../languages/yakut/greeting/audio/dictionary/нет маленькие.mp3"
import greeting_dictionary084 from "../../languages/yakut/greeting/audio/dictionary/да большие.mp3"
import greeting_dictionary085 from "../../languages/yakut/greeting/audio/dictionary/дети учатся или работают.mp3"
import greeting_dictionary086 from "../../languages/yakut/greeting/audio/dictionary/учатся.mp3"
import greeting_dictionary087 from "../../languages/yakut/greeting/audio/dictionary/работают.mp3"
import greeting_dictionary088 from "../../languages/yakut/greeting/audio/dictionary/маленькие учатся большие работают.mp3"
import greeting_dictionary089 from "../../languages/yakut/greeting/audio/dictionary/как зовут детей.mp3"
import greeting_dictionary090 from "../../languages/yakut/greeting/audio/dictionary/есть ли у вас родители.mp3"
import greeting_dictionary091 from "../../languages/yakut/greeting/audio/dictionary/да живут в деревне.mp3"
import greeting_dictionary092 from "../../languages/yakut/greeting/audio/dictionary/мои родители старые.mp3"
import greeting_dictionary093 from "../../languages/yakut/greeting/audio/dictionary/старший брат тракторист.mp3"
import greeting_dictionary094 from "../../languages/yakut/greeting/audio/dictionary/средний брат учитель.mp3"
import greeting_dictionary095 from "../../languages/yakut/greeting/audio/dictionary/младший брат летчик.mp3"
import greeting_dictionary096 from "../../languages/yakut/greeting/audio/dictionary/где работает отец.mp3"
import greeting_dictionary097 from "../../languages/yakut/greeting/audio/dictionary/отец работает в сфере торговли.mp3"
import greeting_dictionary098 from "../../languages/yakut/greeting/audio/dictionary/мать работает в школе.mp3"
import greeting_dictionary099 from "../../languages/yakut/greeting/audio/dictionary/сколько лет отцу.mp3"
import greeting_dictionary100 from "../../languages/yakut/greeting/audio/dictionary/где работаете сами.mp3"
import greeting_dictionary101 from "../../languages/yakut/greeting/audio/dictionary/работаю в мастерской.mp3"
import greeting_dictionary102 from "../../languages/yakut/greeting/audio/dictionary/какую должность занимаете.mp3"
import greeting_dictionary103 from "../../languages/yakut/greeting/audio/dictionary/кем вы работаете.mp3"
import greeting_dictionary104 from "../../languages/yakut/greeting/audio/dictionary/я заведующий.mp3"
import greeting_dictionary105 from "../../languages/yakut/greeting/audio/dictionary/где живете.mp3"
import greeting_dictionary106 from "../../languages/yakut/greeting/audio/dictionary/я живу в деревне.mp3"
import greeting_dictionary107 from "../../languages/yakut/greeting/audio/dictionary/имеете ли свою квартиру.mp3"
import greeting_dictionary108 from "../../languages/yakut/greeting/audio/dictionary/да имею квартиру.mp3"
import greeting_dictionary109 from "../../languages/yakut/greeting/audio/dictionary/живу вместе с родителями.mp3"
import greeting_dictionary110 from "../../languages/yakut/greeting/audio/dictionary/сколько комнат занимаете.mp3"
import greeting_dictionary111 from "../../languages/yakut/greeting/audio/dictionary/занимаем четыре квартиры.mp3"
import greeting_dictionary112 from "../../languages/yakut/greeting/audio/dictionary/по какому адресу живете.mp3"
import greeting_dictionary113 from "../../languages/yakut/greeting/audio/dictionary/живу по улице ойунского.mp3"
import greeting_dictionary114 from "../../languages/yakut/greeting/audio/dictionary/хочу познакомить вас с друзьями.mp3"
import greeting_dictionary115 from "../../languages/yakut/greeting/audio/dictionary/вот лучший друг.mp3"
import greeting_dictionary116 from "../../languages/yakut/greeting/audio/dictionary/это мой родственник.mp3"
import greeting_dictionary117 from "../../languages/yakut/greeting/audio/dictionary/я сын осипова.mp3"
import greeting_dictionary118 from "../../languages/yakut/greeting/audio/dictionary/будьте гостем.mp3"
import greeting_dictionary119 from "../../languages/yakut/greeting/audio/dictionary/чувствуйте себя как дома.mp3"
import greeting_dictionary120 from "../../languages/yakut/greeting/audio/dictionary/когда вы приехали.mp3"
import greeting_dictionary121 from "../../languages/yakut/greeting/audio/dictionary/сегодня утром.mp3"
import greeting_dictionary122 from "../../languages/yakut/greeting/audio/dictionary/давненько вас не видел.mp3"
import greeting_dictionary123 from "../../languages/yakut/greeting/audio/dictionary/вот моя визитная карточка.mp3"
import greeting_dictionary124 from "../../languages/yakut/greeting/audio/dictionary/позвольте представить вас моему мужу.mp3"
import greeting_dictionary125 from "../../languages/yakut/greeting/audio/dictionary/стол сейчас будет накрыт.mp3"
import greeting_dictionary126 from "../../languages/yakut/greeting/audio/dictionary/спасибо мы торопимся.mp3"
import greeting_dictionary127 from "../../languages/yakut/greeting/audio/dictionary/дальше куда поедете.mp3"
import greeting_dictionary128 from "../../languages/yakut/greeting/audio/dictionary/запишите мой адрес.mp3"
import greeting_dictionary129 from "../../languages/yakut/greeting/audio/dictionary/передавайте наилучшие пожелания от меня вашей матери.mp3"
import greeting_dictionary130 from "../../languages/yakut/greeting/audio/dictionary/передавай привет николаю.mp3"
import greeting_dictionary131 from "../../languages/yakut/greeting/audio/dictionary/не пропадайте.mp3"
import greeting_dictionary132 from "../../languages/yakut/greeting/audio/dictionary/с нетерпением жду нашей след встречи.mp3"
import greeting_dictionary133 from "../../languages/yakut/greeting/audio/dictionary/будете в якутске заходите.mp3"
import greeting_dictionary134 from "../../languages/yakut/greeting/audio/dictionary/что вы хотите.mp3"
import greeting_dictionary135 from "../../languages/yakut/greeting/audio/dictionary/я хочу пойти в магазин.mp3"
import greeting_dictionary136 from "../../languages/yakut/greeting/audio/dictionary/я бы отдохнул.mp3"
import greeting_dictionary137 from "../../languages/yakut/greeting/audio/dictionary/я не помешаю.mp3"
import greeting_dictionary138 from "../../languages/yakut/greeting/audio/dictionary/нет ничего.mp3"
import greeting_dictionary139 from "../../languages/yakut/greeting/audio/dictionary/не беспокойся.mp3"
import greeting_dictionary140 from "../../languages/yakut/greeting/audio/dictionary/успокойся все будет в порядке.mp3"
import greeting_dictionary141 from "../../languages/yakut/greeting/audio/dictionary/не обращайте внимания что он сказал.mp3"
import greeting_dictionary142 from "../../languages/yakut/greeting/audio/dictionary/отвезите меня в центр города.mp3"
import greeting_dictionary143 from "../../languages/yakut/greeting/audio/dictionary/вы могли бы показать мне город.mp3"
import greeting_dictionary144 from "../../languages/yakut/greeting/audio/dictionary/я хочу учить якутский язык.mp3"
import greeting_dictionary145 from "../../languages/yakut/greeting/audio/dictionary/спасибо за подарок.mp3"
import greeting_dictionary146 from "../../languages/yakut/greeting/audio/dictionary/сердечно благодарен за теплый прием.mp3"


//FAMILY

//dialogue1
import family_dialogue1_01_l from "../../languages/yakut/family/audio/dialogue1/Привет Айтал.mp3"
import family_dialogue1_01_r from "../../languages/yakut/family/audio/dialogue1/Да у меня большая семья.mp3"
import family_dialogue1_02_l from "../../languages/yakut/family/audio/dialogue1/расскажи мне о своей семье.mp3"
import family_dialogue1_02_r from "../../languages/yakut/family/audio/dialogue1/мою жену зовут сардана.mp3"
import family_dialogue1_03_l from "../../languages/yakut/family/audio/dialogue1/сколько лет детям.mp3"
import family_dialogue1_03_r from "../../languages/yakut/family/audio/dialogue1/сыну девять.mp3"
import family_dialogue1_04_l from "../../languages/yakut/family/audio/dialogue1/где вы живете.mp3"
import family_dialogue1_04_r from "../../languages/yakut/family/audio/dialogue1/мы живем в селе боробул.mp3"
import family_dialogue1_05_l from "../../languages/yakut/family/audio/dialogue1/передавай семье от меня наилучш пожелания.mp3"
import family_dialogue1_05_r from "../../languages/yakut/family/audio/dialogue1/хорошо.mp3"



//dialogue2
import family_dialogue2_01_l from "../../languages/yakut/family/audio/dialogue2/твоя семья большая или маленькая.mp3"
import family_dialogue2_01_r from "../../languages/yakut/family/audio/dialogue2/ни большая ни маленькая.mp3"
import family_dialogue2_02_l from "../../languages/yakut/family/audio/dialogue2/кем работает папа.mp3"
import family_dialogue2_02_r from "../../languages/yakut/family/audio/dialogue2/он водитель.mp3"
import family_dialogue2_03_l from "../../languages/yakut/family/audio/dialogue2/сколько ему лет.mp3"
import family_dialogue2_03_r from "../../languages/yakut/family/audio/dialogue2/ему 38.mp3"
import family_dialogue2_04_l from "../../languages/yakut/family/audio/dialogue2/чем она занимается.mp3"
import family_dialogue2_04_r from "../../languages/yakut/family/audio/dialogue2/работает учителем якутского.mp3"
import family_dialogue2_05_l from "../../languages/yakut/family/audio/dialogue2/что делают твои родители сейчас.mp3"
import family_dialogue2_05_r from "../../languages/yakut/family/audio/dialogue2/мой папа работает сейчас.mp3"
import family_dialogue2_06_l from "../../languages/yakut/family/audio/dialogue2/а где твоя сестренка сейчас.mp3"
import family_dialogue2_06_r from "../../languages/yakut/family/audio/dialogue2/я уверен что она смотрит мультики.mp3"

//dictionary
import family_dictionary001 from "../../languages/yakut/family/audio/dictionary/семья.mp3"
import family_dictionary002 from "../../languages/yakut/family/audio/dictionary/родители.mp3"
import family_dictionary003 from "../../languages/yakut/family/audio/dictionary/папа.mp3"
import family_dictionary004 from "../../languages/yakut/family/audio/dictionary/мама.mp3"
import family_dictionary005 from "../../languages/yakut/family/audio/dictionary/дочь.mp3"
import family_dictionary006 from "../../languages/yakut/family/audio/dictionary/сын.mp3"
import family_dictionary007 from "../../languages/yakut/family/audio/dictionary/старшая сестра.mp3"
import family_dictionary008 from "../../languages/yakut/family/audio/dictionary/младшая сестра.mp3"
import family_dictionary009 from "../../languages/yakut/family/audio/dictionary/родные сестры.mp3"
import family_dictionary010 from "../../languages/yakut/family/audio/dictionary/старший брат.mp3"
import family_dictionary011 from "../../languages/yakut/family/audio/dictionary/младший брат.mp3"
import family_dictionary012 from "../../languages/yakut/family/audio/dictionary/родные братья.mp3"
import family_dictionary013 from "../../languages/yakut/family/audio/dictionary/бабушка.mp3"
import family_dictionary014 from "../../languages/yakut/family/audio/dictionary/дедушка.mp3"
import family_dictionary015 from "../../languages/yakut/family/audio/dictionary/внук.mp3"
import family_dictionary016 from "../../languages/yakut/family/audio/dictionary/невестка.mp3"
import family_dictionary017 from "../../languages/yakut/family/audio/dictionary/сноха.mp3"
import family_dictionary018 from "../../languages/yakut/family/audio/dictionary/невеста.mp3"
import family_dictionary019 from "../../languages/yakut/family/audio/dictionary/зять.mp3"
import family_dictionary020 from "../../languages/yakut/family/audio/dictionary/свекровь.mp3"
import family_dictionary021 from "../../languages/yakut/family/audio/dictionary/свекор.mp3"
import family_dictionary022 from "../../languages/yakut/family/audio/dictionary/теща.mp3"
import family_dictionary023 from "../../languages/yakut/family/audio/dictionary/тесть.mp3"
import family_dictionary024 from "../../languages/yakut/family/audio/dictionary/двоюродные братья.mp3"
import family_dictionary025 from "../../languages/yakut/family/audio/dictionary/родственники.mp3"
import family_dictionary026 from "../../languages/yakut/family/audio/dictionary/супруги.mp3"
import family_dictionary027 from "../../languages/yakut/family/audio/dictionary/супруг.mp3"
import family_dictionary028 from "../../languages/yakut/family/audio/dictionary/супруга.mp3"
import family_dictionary029 from "../../languages/yakut/family/audio/dictionary/мачеха.mp3"
import family_dictionary030 from "../../languages/yakut/family/audio/dictionary/отчим.mp3"
import family_dictionary031 from "../../languages/yakut/family/audio/dictionary/муж (жена).mp3"
import family_dictionary032 from "../../languages/yakut/family/audio/dictionary/разведенный.mp3"
import family_dictionary033 from "../../languages/yakut/family/audio/dictionary/близнецы.mp3"
import family_dictionary034 from "../../languages/yakut/family/audio/dictionary/женатый.mp3"
import family_dictionary035 from "../../languages/yakut/family/audio/dictionary/замужняя.mp3"
import family_dictionary036 from "../../languages/yakut/family/audio/dictionary/холостой.mp3"
import family_dictionary037 from "../../languages/yakut/family/audio/dictionary/вдовец (вдова).mp3"
import family_dictionary038 from "../../languages/yakut/family/audio/dictionary/приемный ребенок.mp3"
import family_dictionary039 from "../../languages/yakut/family/audio/dictionary/ребенок.mp3"
import family_dictionary040 from "../../languages/yakut/family/audio/dictionary/свадьба.mp3"
import family_dictionary041 from "../../languages/yakut/family/audio/dictionary/дом.mp3"
import family_dictionary042 from "../../languages/yakut/family/audio/dictionary/усадьба.mp3"
import family_dictionary043 from "../../languages/yakut/family/audio/dictionary/двор.mp3"

//phrases
import family_phrases001 from "../../languages/yakut/family/audio/phrases/моя семья дружная.mp3"
import family_phrases002 from "../../languages/yakut/family/audio/phrases/это моя семья.mp3"
import family_phrases003 from "../../languages/yakut/family/audio/phrases/моя семья самая лучшая.mp3"
import family_phrases004 from "../../languages/yakut/family/audio/phrases/это моя мама (папа, старшая сестра...).mp3"
import family_phrases005 from "../../languages/yakut/family/audio/phrases/самые любимые и родные люди.mp3"
import family_phrases006 from "../../languages/yakut/family/audio/phrases/наша семейная традиция.mp3"
import family_phrases007 from "../../languages/yakut/family/audio/phrases/я очень люблю своего отцв.mp3"
import family_phrases008 from "../../languages/yakut/family/audio/phrases/мой папа работает в строительстве.mp3"
import family_phrases009 from "../../languages/yakut/family/audio/phrases/большая ли у вас семья_.mp3"
import family_phrases010 from "../../languages/yakut/family/audio/phrases/сколько человек.mp3"
import family_phrases011 from "../../languages/yakut/family/audio/phrases/нас 5 человек.mp3"
import family_phrases012 from "../../languages/yakut/family/audio/phrases/вы женаты(замужем).mp3"
import family_phrases013 from "../../languages/yakut/family/audio/phrases/не женат.mp3"
import family_phrases014 from "../../languages/yakut/family/audio/phrases/мою жену зовут Туйаара.mp3"
import family_phrases015 from "../../languages/yakut/family/audio/phrases/есть ли у вас дети.mp3"
import family_phrases016 from "../../languages/yakut/family/audio/phrases/сколько детей.mp3"
import family_phrases017 from "../../languages/yakut/family/audio/phrases/один ребенок.mp3"
import family_phrases018 from "../../languages/yakut/family/audio/phrases/у меня нет детей.mp3"
import family_phrases019 from "../../languages/yakut/family/audio/phrases/сколько лет дочери.mp3"
import family_phrases020 from "../../languages/yakut/family/audio/phrases/дети большие_.mp3"
import family_phrases021 from "../../languages/yakut/family/audio/phrases/нет маленькие.mp3"
import family_phrases022 from "../../languages/yakut/family/audio/phrases/да большие.mp3"
import family_phrases023 from "../../languages/yakut/family/audio/phrases/дети учатся или работают.mp3"
import family_phrases024 from "../../languages/yakut/family/audio/phrases/учатся.mp3"
import family_phrases025 from "../../languages/yakut/family/audio/phrases/работают.mp3"
import family_phrases026 from "../../languages/yakut/family/audio/phrases/маленькие учатся взрослые работают.mp3"
import family_phrases027 from "../../languages/yakut/family/audio/phrases/как зовут детей.mp3"
import family_phrases028 from "../../languages/yakut/family/audio/phrases/есть у вас родители.mp3"
import family_phrases029 from "../../languages/yakut/family/audio/phrases/да живут в деревне.mp3"
import family_phrases030 from "../../languages/yakut/family/audio/phrases/мои родители старые.mp3"
import family_phrases031 from "../../languages/yakut/family/audio/phrases/я похож на отца.mp3"
import family_phrases032 from "../../languages/yakut/family/audio/phrases/старший брат блогер.mp3"
import family_phrases033 from "../../languages/yakut/family/audio/phrases/где работает отец.mp3"
import family_phrases034 from "../../languages/yakut/family/audio/phrases/отец работает в сфере торговли.mp3"
import family_phrases035 from "../../languages/yakut/family/audio/phrases/мама работает в школе.mp3"
import family_phrases036 from "../../languages/yakut/family/audio/phrases/сколько лет отцу.mp3"
import family_phrases037 from "../../languages/yakut/family/audio/phrases/где работаете сами.mp3"
import family_phrases038 from "../../languages/yakut/family/audio/phrases/в школе работаю.mp3"
import family_phrases039 from "../../languages/yakut/family/audio/phrases/какую должность занимаете.mp3"
import family_phrases040 from "../../languages/yakut/family/audio/phrases/я заведующий.mp3"
import family_phrases041 from "../../languages/yakut/family/audio/phrases/где живете.mp3"
import family_phrases042 from "../../languages/yakut/family/audio/phrases/я живу в деревне.mp3"
import family_phrases043 from "../../languages/yakut/family/audio/phrases/имеете ли свою квартриу.mp3"
import family_phrases044 from "../../languages/yakut/family/audio/phrases/имею квартиру.mp3"
import family_phrases045 from "../../languages/yakut/family/audio/phrases/живу вместе с родителями.mp3"
import family_phrases046 from "../../languages/yakut/family/audio/phrases/сколько комнат занимаете.mp3"
import family_phrases047 from "../../languages/yakut/family/audio/phrases/занимаем 4 комнаты.mp3"
import family_phrases048 from "../../languages/yakut/family/audio/phrases/по какому адресу живете.mp3"
import family_phrases049 from "../../languages/yakut/family/audio/phrases/живу по улице ойунского.mp3"
import family_phrases050 from "../../languages/yakut/family/audio/phrases/семья это важнейшая опора.mp3"

//story
import family_story001 from "../../languages/yakut/family/audio/story/у меня большая семья из 7 человек.mp3"
import family_story002 from "../../languages/yakut/family/audio/story/мы живм в большом доме в деревне.mp3"
import family_story003 from "../../languages/yakut/family/audio/story/мой папа джулус.mp3"
import family_story004 from "../../languages/yakut/family/audio/story/он инженер.mp3"
import family_story005 from "../../languages/yakut/family/audio/story/по работе ему часто приходится ездить.mp3"
import family_story006 from "../../languages/yakut/family/audio/story/он очень трудолюбивый.mp3"
import family_story007 from "../../languages/yakut/family/audio/story/еще он занимается спортом.mp3"
import family_story008 from "../../languages/yakut/family/audio/story/я очень люблю своего отца.mp3"
import family_story009 from "../../languages/yakut/family/audio/story/мою маму зовут аина.mp3"
import family_story010 from "../../languages/yakut/family/audio/story/для меня мама.mp3"
import family_story011 from "../../languages/yakut/family/audio/story/мама работает бухгалтером.mp3"
import family_story012 from "../../languages/yakut/family/audio/story/она хороший специалист.mp3"
import family_story013 from "../../languages/yakut/family/audio/story/очень вкусно готовит.mp3"
import family_story014 from "../../languages/yakut/family/audio/story/я обожаю ее пирожки.mp3"
import family_story015 from "../../languages/yakut/family/audio/story/сестра айта старше меня на 3 года.mp3"
import family_story016 from "../../languages/yakut/family/audio/story/моя сестра учится в 9 классе.mp3"
import family_story017 from "../../languages/yakut/family/audio/story/мы любим учиться и играть с друзьями.mp3"
import family_story018 from "../../languages/yakut/family/audio/story/когда мы приходим домой.mp3"
import family_story019 from "../../languages/yakut/family/audio/story/у меня есть еще младший брат.mp3"
import family_story020 from "../../languages/yakut/family/audio/story/его зовут Айаал.mp3"
import family_story021 from "../../languages/yakut/family/audio/story/он очень любит играть в комп игры.mp3"
import family_story022 from "../../languages/yakut/family/audio/story/с ним мне всегда весело и интересно.mp3"
import family_story023 from "../../languages/yakut/family/audio/story/в нашем доме всегда чисто и тепло.mp3"
import family_story024 from "../../languages/yakut/family/audio/story/наша бабушка.mp3"
import family_story025 from "../../languages/yakut/family/audio/story/дедушка - ветеран.mp3"
import family_story026 from "../../languages/yakut/family/audio/story/интересно слушать дедушку.mp3"
import family_story027 from "../../languages/yakut/family/audio/story/наша бабушка очень добрая.mp3"
import family_story028 from "../../languages/yakut/family/audio/story/мы помогаем бабушке.mp3"
import family_story029 from "../../languages/yakut/family/audio/story/у нас есть кот.mp3"
import family_story030 from "../../languages/yakut/family/audio/story/нашего котенка.mp3"
import family_story031 from "../../languages/yakut/family/audio/story/наша семья очень дружная.mp3"
import family_story032 from "../../languages/yakut/family/audio/story/я хочу чтобы она оставалась такой всегда.mp3"


//ANIMALS

import animals_01 from "../../languages/yakut/animals/audio/5 урок куропатка - вырезанная.mp3"
import animals_02 from "../../languages/yakut/animals/audio/5 урок - заяц вырезанная.mp3"
import animals_03 from "../../languages/yakut/animals/audio/5 урок животный мир якутии - вырезанное.mp3"

//TALES
import tales_01 from "../../languages/yakut/tales/audio/8 урок - гагара вырезанная.mp3"
import tales_02 from "../../languages/yakut/tales/audio/8 урок - водяная крыса вырезанная.mp3"